ACHIEVEMENTS = {
    "first_promotion": {
        "name": "Upward Mobility",
        "description": "Earned your first rank promotion.",
        "category": "score",
        "tier": "silent",
        "yuan_reward": 500,
        "score_reward": 0,
        "badge": None,
        "hint": "Climb the ranks.",
        "secret": False,
    },
    "top_rank": {
        "name": "General Secretary",
        "description": "Reached the highest rank in the Party.",
        "category": "score",
        "tier": "announce",
        "yuan_reward": 50000,
        "score_reward": 3,
        "badge": " | 𝙲𝚊𝚍𝚛𝚎 𝚘𝚏 𝙷𝚘𝚗𝚘𝚛",
        "hint": "The summit of the Party hierarchy awaits the truly devoted.",
        "secret": False,
    },
    "survived_execution": {
        "name": "Reprieve",
        "description": "Recovered from the Execution List.",
        "category": "score",
        "tier": "reaction",
        "yuan_reward": 2000,
        "score_reward": 0,
        "badge": " | Survivor",
        "hint": "Stare into the abyss of social credit, then climb back out.",
        "secret": False,
    },
    "execution_regular": {
        "name": "Frequent Flyer",
        "description": "Landed on the Execution List three separate times. Maybe slow down.",
        "category": "score",
        "tier": "reaction",
        "yuan_reward": 0,
        "score_reward": 0,
        "badge": None,
        "hint": None,
        "secret": True,
    },
    "fastest_climb": {
        "name": "Meteoric Rise",
        "description": "Climbed from the score floor to the top rank.",
        "category": "score",
        "tier": "announce",
        "yuan_reward": 25000,
        "score_reward": 2,
        "badge": " |  ★ 𝑅𝒾𝓈𝒾𝓃𝑔 𝒮𝓉𝒶𝓇 ★",
        "hint": "From the lowest depths to the highest peak.",
        "secret": False,
    },
    "first_10k_yuan": {
        "name": "Small Fortune",
        "description": "Accumulated ¥10,000 lifetime earnings.",
        "category": "economy",
        "tier": "silent",
        "yuan_reward": 500,
        "score_reward": 0,
        "badge": None,
        "hint": "Every fortune starts with a single yuan.",
        "secret": False,
    },
    "millionaire": {
        "name": "Millionaire Comrade",
        "description": "Accumulated ¥1,000,000 lifetime earnings.",
        "category": "economy",
        "tier": "announce",
        "yuan_reward": 20000,
        "score_reward": 1,
        "badge": " | 𝙋𝙚𝙤𝙥𝙡𝙚'𝙨 𝙈𝙞𝙡𝙡𝙞𝙤𝙣𝙖𝙞𝙧𝙚 ˗ˋˏ$ˎˊ˗",
        "hint": "True wealth in service of the People.",
        "secret": False,
    },
    "jackpot_winner": {
        "name": "Lucky Cadre",
        "description": "Won a lottery jackpot.",
        "category": "economy",
        "tier": "announce",
        "yuan_reward": 0,
        "score_reward": 0,
        "badge": " | Jackpot Winner",
        "hint": "Fortune favors the bold gambler.",
        "secret": False,
    },
    "lottery_addict": {
        "name": "Cautionary Tale",
        "description": "Lost ¥100,000 lifetime to the lottery.",
        "category": "joke",
        "tier": "reaction",
        "yuan_reward": 0,
        "score_reward": 0,
        "badge": None,
        "hint": None,
        "secret": True,
    },
    "checkin_streak_7": {
        "name": "Habitual Citizen",
        "description": "Checked in for 7 days in a row.",
        "category": "economy",
        "tier": "silent",
        "yuan_reward": 1000,
        "score_reward": 0,
        "badge": None,
        "hint": "Consistency is a virtue the Party rewards.",
        "secret": False,
    },
    "checkin_streak_30": {
        "name": "Unwavering Loyalty",
        "description": "Checked in for 30 days in a row.",
        "category": "economy",
        "tier": "reaction",
        "yuan_reward": 10000,
        "score_reward": 0,
        "badge": " | ıllıllı  𝒮𝓉𝑒𝒶𝒹𝒻𝒶𝓈𝓉  ıllıllı",
        "hint": "A month of unbroken devotion.",
        "secret": False,
    },
    "checkin_streak_100": {
        "name": "Eternal Vigilance",
        "description": "Checked in for 100 days in a row.",
        "category": "economy",
        "tier": "announce",
        "yuan_reward": 50000,
        "score_reward": 2,
        "badge": " | ♡ 𝙴𝚝𝚎𝚛𝚗𝚊𝚕 𝙲𝚊𝚍𝚛𝚎 ♡",
        "hint": "One hundred days. The Party never forgets devotion like this.",
        "secret": False,
    },
    "first_endorsement": {
        "name": "Vouching",
        "description": "Gave your first endorsement.",
        "category": "social",
        "tier": "silent",
        "yuan_reward": 200,
        "score_reward": 0,
        "badge": None,
        "hint": "Speak well of a fellow citizen.",
        "secret": False,
    },
    "first_rebuke": {
        "name": "Speaking Up",
        "description": "Gave your first rebuke.",
        "category": "social",
        "tier": "silent",
        "yuan_reward": 200,
        "score_reward": 0,
        "badge": None,
        "hint": "Hold a fellow citizen accountable.",
        "secret": False,
    },
    "serial_denouncer": {
        "name": "Vigilant Eyes",
        "description": "Denounced five different citizens.",
        "category": "social",
        "tier": "reaction",
        "yuan_reward": 5000,
        "score_reward": 0,
        "badge": " | Watchful",
        "hint": "Report wrongdoing wherever you see it. Repeatedly.",
        "secret": False,
    },
    "frequently_denounced": {
        "name": "Person of Interest",
        "description": "Been denounced by five different citizens.",
        "category": "joke",
        "tier": "reaction",
        "yuan_reward": 0,
        "score_reward": 0,
        "badge": None,
        "hint": None,
        "secret": True,
    },
    "fundraiser_success": {
        "name": "Community Organizer",
        "description": "Created a fundraiser that reached its goal.",
        "category": "social",
        "tier": "reaction",
        "yuan_reward": 5000,
        "score_reward": 0,
        "badge": " | Organizer",
        "hint": "Rally the People behind a worthy cause.",
        "secret": False,
    },
    "first_trade": {
        "name": "Market Debut",
        "description": "Made your first stock trade.",
        "category": "markets",
        "tier": "silent",
        "yuan_reward": 500,
        "score_reward": 0,
        "badge": None,
        "hint": "Step onto the trading floor.",
        "secret": False,
    },
    "first_turbo": {
        "name": "High Roller",
        "description": "Opened your first turbo certificate position.",
        "category": "markets",
        "tier": "silent",
        "yuan_reward": 500,
        "score_reward": 0,
        "badge": None,
        "hint": "Leverage carries risk and reward in equal measure.",
        "secret": False,
    },
    "knocked_out": {
        "name": "Margin Call",
        "description": "Got knocked out of a turbo position.",
        "category": "joke",
        "tier": "reaction",
        "yuan_reward": 0,
        "score_reward": 0,
        "badge": None,
        "hint": None,
        "secret": True,
    },
    "realized_50k_profit": {
        "name": "Savvy Investor",
        "description": "Realized ¥50,000 in lifetime stock profit.",
        "category": "markets",
        "tier": "reaction",
        "yuan_reward": 10000,
        "score_reward": 0,
        "badge": " | ꜱᴀᴠᴠʏ ɪɴᴠᴇꜱᴛᴏʀ",
        "hint": "Buy low, sell high, repeat.",
        "secret": False,
    },
    "held_through_halt": {
        "name": "Nerves of Steel",
        "description": "Held a position through a circuit-breaker halt.",
        "category": "markets",
        "tier": "reaction",
        "yuan_reward": 5000,
        "score_reward": 0,
        "badge": None,
        "hint": "Volatility tests the resolve of every investor.",
        "secret": False,
    },
    "global_trader": {
        "name": "Global Trader",
        "description": "Traded on all three exchanges: NYSE, LSE, and TSE.",
        "category": "markets",
        "tier": "announce",
        "yuan_reward": 15000,
        "score_reward": 1,
        "badge": " | Globetrotter",
        "hint": "The sun never sets on a determined trader.",
        "secret": False,
    },
    "propaganda_winner": {
        "name": "People's Choice",
        "description": "Won a propaganda event.",
        "category": "propaganda",
        "tier": "reaction",
        "yuan_reward": 5000,
        "score_reward": 0,
        "badge": " | Acclaimed",
        "hint": "Craft propaganda worthy of the masses' approval.",
        "secret": False,
    },
    "propaganda_banned": {
        "name": "Thought Crime",
        "description": "Got banned from a propaganda event for a banned-topic submission.",
        "category": "joke",
        "tier": "reaction",
        "yuan_reward": 0,
        "score_reward": 0,
        "badge": None,
        "hint": None,
        "secret": True,
    },
    "first_vote": {
        "name": "Civic Duty",
        "description": "Voted for the bot on top.gg.",
        "category": "propaganda",
        "tier": "silent",
        "yuan_reward": 1000,
        "score_reward": 0,
        "badge": None,
        "hint": "Cast your vote and be rewarded for it.",
        "secret": False,
    },
    "first_confession": {
        "name": "Self-Criticism",
        "description": "Used /confess for the first time.",
        "category": "propaganda",
        "tier": "silent",
        "yuan_reward": 300,
        "score_reward": 0,
        "badge": None,
        "hint": "Confess your sins to the Party.",
        "secret": False,
    },
}


def get_achievement(achievement_id: str) -> dict | None:
    return ACHIEVEMENTS.get(achievement_id)


def achievements_by_category() -> dict[str, list[str]]:
    grouped: dict[str, list[str]] = {}
    for aid, data in ACHIEVEMENTS.items():
        grouped.setdefault(data["category"], []).append(aid)
    return grouped
