ACHIEVEMENTS = {
    "first_promotion": {
        "name": "Upward Mobility",
        "description": "Earned your first rank promotion.",
        "category": "score",
        "tier": "silent",
        "yuan_reward": 500,
        "score_reward": 0,
        "badge": None,
        "hint": "Climb the ranks.",
        "secret": False,
    },
    "top_rank": {
        "name": "General Secretary",
        "description": "Reached the highest rank in the Party.",
        "category": "score",
        "tier": "announce",
        "yuan_reward": 50000,
        "score_reward": 3,
        "badge": " | ★ 𝙲𝚊𝚍𝚛𝚎 𝚘𝚏 𝙷𝚘𝚗𝚘𝚛 ★",
        "hint": "The summit of the Party hierarchy awaits the truly devoted.",
        "secret": False,
    },
    "survived_execution": {
        "name": "Reprieve",
        "description": "Recovered from the Execution List.",
        "category": "score",
        "tier": "reaction",
        "yuan_reward": 2000,
        "score_reward": 0,
        "badge": " | ꜱᴜʀᴠɪᴠᴏʀ",
        "hint": "Stare into the abyss of social credit, then climb back out.",
        "secret": False,
    },
    "execution_regular": {
        "name": "Frequent Flyer",
        "description": "Landed on the Execution List three separate times. Maybe slow down.",
        "category": "score",
        "tier": "reaction",
        "yuan_reward": 0,
        "score_reward": 0,
        "badge": None,
        "hint": None,
        "secret": True,
    },
    "fastest_climb": {
        "name": "Meteoric Rise",
        "description": "Climbed from the score floor to the top rank.",
        "category": "score",
        "tier": "announce",
        "yuan_reward": 25000,
        "score_reward": 2,
        "badge": " | ★ 𝚁𝚒𝚜𝚒𝚗𝚐 𝚂𝚝𝚊𝚛 ★",
        "hint": "From the lowest depths to the highest peak.",
        "secret": False,
    },
    "first_10k_yuan": {
        "name": "Small Fortune",
        "description": "Accumulated ¥10,000 lifetime earnings.",
        "category": "economy",
        "tier": "silent",
        "yuan_reward": 500,
        "score_reward": 0,
        "badge": None,
        "hint": "Every fortune starts with a single yuan.",
        "secret": False,
    },
    "millionaire": {
        "name": "Millionaire Comrade",
        "description": "Accumulated ¥1,000,000 lifetime earnings.",
        "category": "economy",
        "tier": "announce",
        "yuan_reward": 20000,
        "score_reward": 1,
        "badge": " | ★ 𝙿𝚎𝚘𝚙𝚕𝚎'𝚜 𝙼𝚒𝚕𝚕𝚒𝚘𝚗𝚊𝚒𝚛𝚎 ★",
        "hint": "True wealth in service of the People.",
        "secret": False,
    },
    "jackpot_winner": {
        "name": "Lucky Cadre",
        "description": "Won a lottery jackpot.",
        "category": "economy",
        "tier": "announce",
        "yuan_reward": 0,
        "score_reward": 0,
        "badge": " | ★ 𝙹𝚊𝚌𝚔𝚙𝚘𝚝 𝚆𝚒𝚗𝚗𝚎𝚛 ★",
        "hint": "Fortune favors the bold gambler.",
        "secret": False,
    },
    "lottery_addict": {
        "name": "Cautionary Tale",
        "description": "Lost ¥100,000 lifetime to the lottery.",
        "category": "joke",
        "tier": "reaction",
        "yuan_reward": 0,
        "score_reward": 0,
        "badge": None,
        "hint": None,
        "secret": True,
    },
    "checkin_streak_7": {
        "name": "Habitual Citizen",
        "description": "Checked in for 7 days in a row.",
        "category": "economy",
        "tier": "silent",
        "yuan_reward": 1000,
        "score_reward": 0,
        "badge": None,
        "hint": "Consistency is a virtue the Party rewards.",
        "secret": False,
    },
    "checkin_streak_30": {
        "name": "Unwavering Loyalty",
        "description": "Checked in for 30 days in a row.",
        "category": "economy",
        "tier": "reaction",
        "yuan_reward": 10000,
        "score_reward": 0,
        "badge": " | ꜱᴛᴇᴀᴅꜰᴀꜱᴛ",
        "hint": "A month of unbroken devotion.",
        "secret": False,
    },
    "checkin_streak_100": {
        "name": "Eternal Vigilance",
        "description": "Checked in for 100 days in a row.",
        "category": "economy",
        "tier": "announce",
        "yuan_reward": 50000,
        "score_reward": 2,
        "badge": " | ★ 𝙴𝚝𝚎𝚛𝚗𝚊𝚕 𝙲𝚊𝚍𝚛𝚎 ★",
        "hint": "One hundred days. The Party never forgets devotion like this.",
        "secret": False,
    },
    "first_endorsement": {
        "name": "Vouching",
        "description": "Gave your first endorsement.",
        "category": "social",
        "tier": "silent",
        "yuan_reward": 200,
        "score_reward": 0,
        "badge": None,
        "hint": "Speak well of a fellow citizen.",
        "secret": False,
    },
    "first_rebuke": {
        "name": "Speaking Up",
        "description": "Gave your first rebuke.",
        "category": "social",
        "tier": "silent",
        "yuan_reward": 200,
        "score_reward": 0,
        "badge": None,
        "hint": "Hold a fellow citizen accountable.",
        "secret": False,
    },
    "serial_denouncer": {
        "name": "Vigilant Eyes",
        "description": "Denounced five different citizens.",
        "category": "social",
        "tier": "reaction",
        "yuan_reward": 5000,
        "score_reward": 0,
        "badge": " | ᴡᴀᴛᴄʜꜰᴜʟ",
        "hint": "Report wrongdoing wherever you see it. Repeatedly.",
        "secret": False,
    },
    "frequently_denounced": {
        "name": "Person of Interest",
        "description": "Been denounced by five different citizens.",
        "category": "joke",
        "tier": "reaction",
        "yuan_reward": 0,
        "score_reward": 0,
        "badge": None,
        "hint": None,
        "secret": True,
    },
    "fundraiser_success": {
        "name": "Community Organizer",
        "description": "Created a fundraiser that reached its goal.",
        "category": "social",
        "tier": "reaction",
        "yuan_reward": 5000,
        "score_reward": 0,
        "badge": " | ᴏʀɢᴀɴɪᴢᴇʀ",
        "hint": "Rally the People behind a worthy cause.",
        "secret": False,
    },
    "first_trade": {
        "name": "Market Debut",
        "description": "Made your first stock trade.",
        "category": "markets",
        "tier": "silent",
        "yuan_reward": 500,
        "score_reward": 0,
        "badge": None,
        "hint": "Step onto the trading floor.",
        "secret": False,
    },
    "first_turbo": {
        "name": "High Roller",
        "description": "Opened your first turbo certificate position.",
        "category": "markets",
        "tier": "silent",
        "yuan_reward": 500,
        "score_reward": 0,
        "badge": None,
        "hint": "Leverage carries risk and reward in equal measure.",
        "secret": False,
    },
    "knocked_out": {
        "name": "Margin Call",
        "description": "Got knocked out of a turbo position.",
        "category": "joke",
        "tier": "reaction",
        "yuan_reward": 0,
        "score_reward": 0,
        "badge": None,
        "hint": None,
        "secret": True,
    },
    "realized_50k_profit": {
        "name": "Savvy Investor",
        "description": "Realized ¥50,000 in lifetime stock profit.",
        "category": "markets",
        "tier": "reaction",
        "yuan_reward": 10000,
        "score_reward": 0,
        "badge": " | ꜱᴀᴠᴠʏ ɪɴᴠᴇꜱᴛᴏʀ",
        "hint": "Buy low, sell high, repeat.",
        "secret": False,
    },
    "held_through_halt": {
        "name": "Nerves of Steel",
        "description": "Held a position through a circuit-breaker halt.",
        "category": "markets",
        "tier": "reaction",
        "yuan_reward": 5000,
        "score_reward": 0,
        "badge": None,
        "hint": "Volatility tests the resolve of every investor.",
        "secret": False,
    },
    "global_trader": {
        "name": "Global Trader",
        "description": "Traded on all three exchanges: NYSE, LSE, and TSE.",
        "category": "markets",
        "tier": "announce",
        "yuan_reward": 15000,
        "score_reward": 1,
        "badge": " | ★ 𝙶𝚕𝚘𝚋𝚎𝚝𝚛𝚘𝚝𝚝𝚎𝚛 ★",
        "hint": "The sun never sets on a determined trader.",
        "secret": False,
    },
    "propaganda_winner": {
        "name": "People's Choice",
        "description": "Won a propaganda event.",
        "category": "propaganda",
        "tier": "reaction",
        "yuan_reward": 5000,
        "score_reward": 0,
        "badge": " | ᴀᴄᴄʟᴀɪᴍᴇᴅ",
        "hint": "Craft propaganda worthy of the masses' approval.",
        "secret": False,
    },
    "propaganda_banned": {
        "name": "Thought Crime",
        "description": "Got banned from a propaganda event for a banned-topic submission.",
        "category": "joke",
        "tier": "reaction",
        "yuan_reward": 0,
        "score_reward": 0,
        "badge": None,
        "hint": None,
        "secret": True,
    },
    "first_vote": {
        "name": "Civic Duty",
        "description": "Voted for the bot on top.gg.",
        "category": "propaganda",
        "tier": "silent",
        "yuan_reward": 1000,
        "score_reward": 0,
        "badge": None,
        "hint": "Cast your vote and be rewarded for it.",
        "secret": False,
    },
    "first_confession": {
        "name": "Self-Criticism",
        "description": "Used /confess for the first time.",
        "category": "propaganda",
        "tier": "silent",
        "yuan_reward": 300,
        "score_reward": 0,
        "badge": None,
        "hint": "Confess your sins to the Party.",
        "secret": False,
    },
    "high_roller_loss": {
        "name": "House Always Wins",
        "description": "Lost ¥500,000 lifetime to the lottery.",
        "category": "joke",
        "tier": "announce",
        "yuan_reward": 0,
        "score_reward": 0,
        "badge": None,
        "hint": None,
        "secret": True,
    },
    "shopaholic_1": {
        "name": "Frequent Shopper",
        "description": "Made 25 purchases from the shop.",
        "category": "economy",
        "tier": "silent",
        "yuan_reward": 300,
        "score_reward": 0,
        "badge": None,
        "hint": "The shop has plenty to offer the dedicated consumer.",
        "secret": False,
        "milestone_key": "purchases_made",
        "threshold": 25,
    },
    "shopaholic_2": {
        "name": "Loyal Consumer",
        "description": "Made 100 purchases from the shop.",
        "category": "economy",
        "tier": "reaction",
        "yuan_reward": 5000,
        "score_reward": 0,
        "badge": " | ᴄᴏɴꜱᴜᴍᴇʀ",
        "hint": "A century of transactions in service of the state economy.",
        "secret": False,
        "milestone_key": "purchases_made",
        "threshold": 100,
    },
    "shopaholic_3": {
        "name": "State Procurement Office",
        "description": "Made 500 purchases from the shop.",
        "category": "economy",
        "tier": "announce",
        "yuan_reward": 20000,
        "score_reward": 1,
        "badge": " | ★ 𝚂𝚝𝚊𝚝𝚎 𝙿𝚛𝚘𝚌𝚞𝚛𝚎𝚖𝚎𝚗𝚝 𝙾𝚏𝚏𝚒𝚌𝚎 ★",
        "hint": "Single-handedly keep the shop in business.",
        "secret": False,
        "milestone_key": "purchases_made",
        "threshold": 500,
    },
    "model_citizen_1": {
        "name": "Model Citizen",
        "description": "Sent 250 messages with positive sentiment.",
        "category": "score",
        "tier": "silent",
        "yuan_reward": 500,
        "score_reward": 0,
        "badge": None,
        "hint": "Speak well, and speak often.",
        "secret": False,
        "milestone_key": "messages_positive",
        "threshold": 250,
    },
    "model_citizen_2": {
        "name": "Exemplary Voice",
        "description": "Sent 1,000 messages with positive sentiment.",
        "category": "score",
        "tier": "reaction",
        "yuan_reward": 8000,
        "score_reward": 0,
        "badge": " | ᴇxᴇᴍᴘʟᴀʀʏ ᴠᴏɪᴄᴇ",
        "hint": "A thousand kind words for the Motherland.",
        "secret": False,
        "milestone_key": "messages_positive",
        "threshold": 1000,
    },
    "model_citizen_3": {
        "name": "Voice of the Nation",
        "description": "Sent 5,000 messages with positive sentiment.",
        "category": "score",
        "tier": "announce",
        "yuan_reward": 30000,
        "score_reward": 2,
        "badge": " | ★ 𝚅𝚘𝚒𝚌𝚎 𝚘𝚏 𝚝𝚑𝚎 𝙽𝚊𝚝𝚒𝚘𝚗 ★",
        "hint": "Five thousand messages of unwavering positivity.",
        "secret": False,
        "milestone_key": "messages_positive",
        "threshold": 5000,
    },
    "dissident_voice_1": {
        "name": "Dissident Voice",
        "description": "Sent 100 messages with negative sentiment.",
        "category": "joke",
        "tier": "reaction",
        "yuan_reward": 0,
        "score_reward": 0,
        "badge": None,
        "hint": None,
        "secret": True,
        "milestone_key": "messages_negative",
        "threshold": 100,
    },
    "dissident_voice_2": {
        "name": "Enemy of the State",
        "description": "Sent 500 messages with negative sentiment.",
        "category": "joke",
        "tier": "announce",
        "yuan_reward": 0,
        "score_reward": 0,
        "badge": None,
        "hint": None,
        "secret": True,
        "milestone_key": "messages_negative",
        "threshold": 500,
    },
    "bureaucratic_drone_1": {
        "name": "Bureaucratic Drone",
        "description": "Sent 250 messages of routine, neutral content.",
        "category": "joke",
        "tier": "silent",
        "yuan_reward": 0,
        "score_reward": 0,
        "badge": None,
        "hint": "Say nothing of consequence. Often.",
        "secret": False,
        "milestone_key": "messages_neutral",
        "threshold": 250,
    },
    "bureaucratic_drone_2": {
        "name": "Office of Forms and Filings",
        "description": "Sent 1,000 messages of routine, neutral content.",
        "category": "joke",
        "tier": "reaction",
        "yuan_reward": 0,
        "score_reward": 0,
        "badge": None,
        "hint": "A thousand entries in the ledger of the unremarkable.",
        "secret": False,
        "milestone_key": "messages_neutral",
        "threshold": 1000,
    },
    "repeat_offender_1": {
        "name": "Habitual Confessor",
        "description": "Used /confess 10 times.",
        "category": "propaganda",
        "tier": "silent",
        "yuan_reward": 500,
        "score_reward": 0,
        "badge": None,
        "hint": "Confession is good for the soul. Repeatedly.",
        "secret": False,
        "milestone_key": "confessions_made",
        "threshold": 10,
    },
    "repeat_offender_2": {
        "name": "Penitent",
        "description": "Used /confess 50 times.",
        "category": "propaganda",
        "tier": "reaction",
        "yuan_reward": 8000,
        "score_reward": 0,
        "badge": " | ᴘᴇɴɪᴛᴇɴᴛ",
        "hint": "Fifty confessions and counting.",
        "secret": False,
        "milestone_key": "confessions_made",
        "threshold": 50,
    },
    "civic_duty_2": {
        "name": "Civic Regular",
        "description": "Voted for the bot on top.gg 10 times.",
        "category": "propaganda",
        "tier": "silent",
        "yuan_reward": 1000,
        "score_reward": 0,
        "badge": None,
        "hint": "Cast your vote, again and again.",
        "secret": False,
        "milestone_key": "topgg_votes_total",
        "threshold": 10,
    },
    "civic_duty_3": {
        "name": "Civic Champion",
        "description": "Voted for the bot on top.gg 50 times.",
        "category": "propaganda",
        "tier": "reaction",
        "yuan_reward": 10000,
        "score_reward": 0,
        "badge": " | ᴄɪᴠɪᴄ ᴄʜᴀᴍᴘɪᴏɴ",
        "hint": "Fifty votes cast in service of the bureau.",
        "secret": False,
        "milestone_key": "topgg_votes_total",
        "threshold": 50,
    },
    "financier_1": {
        "name": "Financier",
        "description": "Completed 25 yuan transfers.",
        "category": "economy",
        "tier": "silent",
        "yuan_reward": 500,
        "score_reward": 0,
        "badge": None,
        "hint": "Move money through the system.",
        "secret": False,
        "milestone_key": "transfers_completed",
        "threshold": 25,
    },
    "financier_2": {
        "name": "State Bank",
        "description": "Completed 100 yuan transfers.",
        "category": "economy",
        "tier": "reaction",
        "yuan_reward": 8000,
        "score_reward": 0,
        "badge": " | ꜰɪɴᴀɴᴄɪᴇʀ",
        "hint": "A hundred transfers processed without incident.",
        "secret": False,
        "milestone_key": "transfers_completed",
        "threshold": 100,
    },
    "big_spender_1": {
        "name": "Big Spender",
        "description": "Transferred ¥50,000 or more in a single transfer.",
        "category": "economy",
        "tier": "silent",
        "yuan_reward": 500,
        "score_reward": 0,
        "badge": None,
        "hint": "Move a fortune in a single transaction.",
        "secret": False,
        "milestone_key": "large_transfers_made",
        "threshold": 1,
    },
    "big_spender_2": {
        "name": "Whale",
        "description": "Transferred ¥50,000 or more in a single transfer, 10 separate times.",
        "category": "economy",
        "tier": "reaction",
        "yuan_reward": 10000,
        "score_reward": 0,
        "badge": " | ᴡʜᴀʟᴇ",
        "hint": "Ten fortunes moved without hesitation.",
        "secret": False,
        "milestone_key": "large_transfers_made",
        "threshold": 10,
    },
    "clean_record_7": {
        "name": "Clean Record",
        "description": "Went 7 days without a negative score action.",
        "category": "score",
        "tier": "silent",
        "yuan_reward": 1000,
        "score_reward": 0,
        "badge": None,
        "hint": "A week of good behavior.",
        "secret": False,
        "milestone_key": "clean_streak_days",
        "threshold": 7,
    },
    "clean_record_14": {
        "name": "Spotless",
        "description": "Went 14 days without a negative score action.",
        "category": "score",
        "tier": "reaction",
        "yuan_reward": 5000,
        "score_reward": 0,
        "badge": " | ꜱᴘᴏᴛʟᴇꜱꜱ",
        "hint": "Two weeks free of any infraction.",
        "secret": False,
        "milestone_key": "clean_streak_days",
        "threshold": 14,
    },
    "clean_record_30": {
        "name": "Immaculate Record",
        "description": "Went 30 days without a negative score action.",
        "category": "score",
        "tier": "announce",
        "yuan_reward": 20000,
        "score_reward": 2,
        "badge": " | ★ 𝙸𝚖𝚖𝚊𝚌𝚞𝚕𝚊𝚝𝚎 𝚁𝚎𝚌𝚘𝚛𝚍 ★",
        "hint": "A full month of flawless conduct.",
        "secret": False,
        "milestone_key": "clean_streak_days",
        "threshold": 30,
    },
    "devoted_supporter_1": {
        "name": "Devoted Supporter",
        "description": "Reacted to the daily propaganda poster 7 days in a row.",
        "category": "propaganda",
        "tier": "silent",
        "yuan_reward": 500,
        "score_reward": 0,
        "badge": None,
        "hint": "Show your support, day after day.",
        "secret": False,
        "milestone_key": "poster_heart_streak",
        "threshold": 7,
    },
    "devoted_supporter_2": {
        "name": "Devoted",
        "description": "Reacted to the daily propaganda poster 30 days in a row.",
        "category": "propaganda",
        "tier": "announce",
        "yuan_reward": 15000,
        "score_reward": 1,
        "badge": " | ★ 𝙳𝚎𝚟𝚘𝚝𝚎𝚍 ★",
        "hint": "A month of unbroken support for the daily poster.",
        "secret": False,
        "milestone_key": "poster_heart_streak",
        "threshold": 30,
    },
    "persistent_dissent": {
        "name": "Persistent Dissent",
        "description": "Reacted negatively to the daily propaganda poster 7 days in a row.",
        "category": "joke",
        "tier": "reaction",
        "yuan_reward": 0,
        "score_reward": 0,
        "badge": None,
        "hint": None,
        "secret": True,
        "milestone_key": "poster_rage_streak",
        "threshold": 7,
    },
    "vote_streak_1": {
        "name": "Reliable Voter",
        "description": "Voted for the bot on top.gg 3 days in a row.",
        "category": "propaganda",
        "tier": "silent",
        "yuan_reward": 500,
        "score_reward": 0,
        "badge": None,
        "hint": "Vote, then vote again tomorrow.",
        "secret": False,
        "milestone_key": "topgg_vote_streak",
        "threshold": 3,
    },
    "vote_streak_2": {
        "name": "Unbroken Ballot",
        "description": "Voted for the bot on top.gg 10 days in a row.",
        "category": "propaganda",
        "tier": "reaction",
        "yuan_reward": 8000,
        "score_reward": 0,
        "badge": " | ʀᴇʟɪᴀʙʟᴇ ᴠᴏᴛᴇʀ",
        "hint": "Ten consecutive days of civic duty.",
        "secret": False,
        "milestone_key": "topgg_vote_streak",
        "threshold": 10,
    },
    "day_trader_1": {
        "name": "Day Trader",
        "description": "Traded on the markets 7 days in a row.",
        "category": "markets",
        "tier": "silent",
        "yuan_reward": 500,
        "score_reward": 0,
        "badge": None,
        "hint": "Show up to the trading floor every day.",
        "secret": False,
        "milestone_key": "stock_invest_streak",
        "threshold": 7,
    },
    "day_trader_2": {
        "name": "Wall Street Cadre",
        "description": "Traded on the markets 30 days in a row.",
        "category": "markets",
        "tier": "announce",
        "yuan_reward": 15000,
        "score_reward": 1,
        "badge": " | ★ 𝙳𝚊𝚢 𝚃𝚛𝚊𝚍𝚎𝚛 ★",
        "hint": "A month without missing a single trading day.",
        "secret": False,
        "milestone_key": "stock_invest_streak",
        "threshold": 30,
    },
    "supportive_citizen_1": {
        "name": "Supportive Citizen",
        "description": "Endorsed a fellow citizen 7 days in a row.",
        "category": "social",
        "tier": "silent",
        "yuan_reward": 500,
        "score_reward": 0,
        "badge": None,
        "hint": "Lift up your fellow citizens, every day.",
        "secret": False,
        "milestone_key": "endorse_streak",
        "threshold": 7,
    },
    "supportive_citizen_2": {
        "name": "Pillar of the Community",
        "description": "Endorsed a fellow citizen 30 days in a row.",
        "category": "social",
        "tier": "reaction",
        "yuan_reward": 10000,
        "score_reward": 0,
        "badge": " | ꜱᴜᴘᴘᴏʀᴛɪᴠᴇ",
        "hint": "A month of consistent encouragement.",
        "secret": False,
        "milestone_key": "endorse_streak",
        "threshold": 30,
    },
    "watchdog_1": {
        "name": "Watchdog",
        "description": "Rebuked a fellow citizen 7 days in a row.",
        "category": "social",
        "tier": "silent",
        "yuan_reward": 500,
        "score_reward": 0,
        "badge": None,
        "hint": "Hold your fellow citizens accountable, every day.",
        "secret": False,
        "milestone_key": "rebuke_streak",
        "threshold": 7,
    },
    "watchdog_2": {
        "name": "Internal Affairs",
        "description": "Rebuked a fellow citizen 30 days in a row.",
        "category": "social",
        "tier": "reaction",
        "yuan_reward": 10000,
        "score_reward": 0,
        "badge": " | ᴡᴀᴛᴄʜᴅᴏɢ",
        "hint": "A month of relentless scrutiny.",
        "secret": False,
        "milestone_key": "rebuke_streak",
        "threshold": 30,
    },
    # ── WAIFU BUREAU ─────────────────────────────────────────────────────────
    "first_roll": {
        "name": "The Bureau Calls",
        "description": "Rolled in the Waifu Bureau for the first time.",
        "category": "gacha",
        "tier": "silent",
        "yuan_reward": 100,
        "score_reward": 0,
        "badge": None,
        "hint": "Try your luck at the bureau.",
        "secret": False,
    },
    "first_claim": {
        "name": "Taken",
        "description": "Claimed your first waifu.",
        "category": "gacha",
        "tier": "silent",
        "yuan_reward": 500,
        "score_reward": 0,
        "badge": None,
        "hint": "React to a roll to claim your first historical soulmate.",
        "secret": False,
    },
    "first_dupe": {
        "name": "Already Taken",
        "description": "Reacted to a duplicate roll and received yuan compensation.",
        "category": "gacha",
        "tier": "silent",
        "yuan_reward": 200,
        "score_reward": 0,
        "badge": None,
        "hint": "Someone else got there first.",
        "secret": False,
    },
    "claimed_legendary": {
        "name": "Founding Father",
        "description": "Claimed a legendary-rarity waifu.",
        "category": "gacha",
        "tier": "announce",
        "yuan_reward": 5000,
        "score_reward": 1,
        "badge": " | ★ 𝙻𝚎𝚐𝚎𝚗𝚍𝚊𝚛𝚢 𝙷𝚊𝚛𝚎𝚖 ★",
        "hint": "The rarest figures demand the most luck.",
        "secret": False,
    },
    "first_divorce": {
        "name": "Irreconcilable Differences",
        "description": "Divorced your first waifu.",
        "category": "gacha",
        "tier": "silent",
        "yuan_reward": 0,
        "score_reward": 0,
        "badge": None,
        "hint": "Politics makes for complicated marriages.",
        "secret": False,
    },
    "first_waifu_trade": {
        "name": "Diplomatic Exchange",
        "description": "Completed your first waifu trade.",
        "category": "gacha",
        "tier": "silent",
        "yuan_reward": 500,
        "score_reward": 0,
        "badge": None,
        "hint": "Trade waifus with a fellow citizen.",
        "secret": False,
    },
    "wishlist_fulfilled": {
        "name": "Long-Awaited",
        "description": "Claimed a waifu that was on your wishlist.",
        "category": "gacha",
        "tier": "reaction",
        "yuan_reward": 2000,
        "score_reward": 0,
        "badge": " | ᴡɪꜱʜꜰᴜʟ",
        "hint": "Add to your wishlist, then roll until you get them.",
        "secret": False,
    },
    "gacha_collector_1": {
        "name": "Building a Harem",
        "description": "Claimed 10 waifus total.",
        "category": "gacha",
        "tier": "silent",
        "yuan_reward": 1000,
        "score_reward": 0,
        "badge": None,
        "hint": "Collect ten figures for the bureau registry.",
        "secret": False,
        "milestone_key": "gacha_claims_total",
        "threshold": 10,
    },
    "gacha_collector_2": {
        "name": "Political Hoarder",
        "description": "Claimed 50 waifus total.",
        "category": "gacha",
        "tier": "reaction",
        "yuan_reward": 5000,
        "score_reward": 0,
        "badge": " | ᴄᴏʟʟᴇᴄᴛᴏʀ",
        "hint": "Fifty figures in the bureau's registry.",
        "secret": False,
        "milestone_key": "gacha_claims_total",
        "threshold": 50,
    },
    "gacha_collector_3": {
        "name": "The Grand Harem",
        "description": "Claimed 100 waifus total.",
        "category": "gacha",
        "tier": "announce",
        "yuan_reward": 20000,
        "score_reward": 2,
        "badge": " | ★ 𝙶𝚛𝚊𝚗𝚍 𝙷𝚊𝚛𝚎𝚖 ★",
        "hint": "One hundred figures under one roof.",
        "secret": False,
        "milestone_key": "gacha_claims_total",
        "threshold": 100,
    },
    "serial_divorcee": {
        "name": "Irreconcilable",
        "description": "Divorced 10 waifus. They deserved better.",
        "category": "joke",
        "tier": "reaction",
        "yuan_reward": 0,
        "score_reward": 0,
        "badge": None,
        "hint": None,
        "secret": True,
        "milestone_key": "gacha_divorces",
        "threshold": 10,
    },
    "completionist": {
        "name": "Paragon of the Party",
        "description": "Unlocked every other achievement.",
        "category": "meta",
        "tier": "announce",
        "yuan_reward": 100000,
        "score_reward": 5,
        "badge": " | ★★ 𝙿𝚊𝚛𝚊𝚐𝚘𝚗 𝚘𝚏 𝚝𝚑𝚎 𝙿𝚊𝚛𝚝𝚢 ★★",
        "hint": "Unlock every other achievement in the bureau's record.",
        "secret": False,
    },
}


def get_achievement(achievement_id: str) -> dict | None:
    return ACHIEVEMENTS.get(achievement_id)


def achievements_by_category() -> dict[str, list[str]]:
    grouped: dict[str, list[str]] = {}
    for aid, data in ACHIEVEMENTS.items():
        grouped.setdefault(data["category"], []).append(aid)
    return grouped
