SHOP_ITEMS = {
    # --- Core system ---
    "report": {
        "name": "Citizen Report",
        "description": "Docks -2.00 from target's rating. Silent. Entry logged in their permanent record.",
        "cost": 2500,
        "requires_target": True,
        "requires_text": False,
        "category": "core",
    },
    "denounce": {
        "name": "Public Denouncement",
        "description": "Issues a public censure. Docks -20.00 from target's rating. Claims any active investigation bounty. 48h cooldown per target.",
        "cost": 12000,
        "requires_target": True,
        "requires_text": True,
        "category": "core",
    },

    "rehabilitate": {
        "name": "Rehabilitation Program",
        "description": "Restores +3.00 rating. Cost doubles with each use. Gift-eligible.",
        "cost": 3000,
        "requires_target": False,
        "requires_text": False,
        "category": "core",
    },
    "appeal": {
        "name": "Appeal Process",
        "description": "Halves the next incoming penalty. Triggers only on deliberate actions of -1.00 or worse. Single use · 12h window. Gift-eligible.",
        "cost": 2500,
        "requires_target": False,
        "requires_text": False,
        "duration": 43200,
        "category": "core",
    },
    "exception": {
        "name": "Administrative Exception",
        "description": "Fully nullifies the next negative action filed against this citizen. Single use · 24h window. Gift-eligible.",
        "cost": 12000,
        "requires_target": False,
        "requires_text": False,
        "duration": 86400,
        "category": "core",
    },
    "reeducation": {
        "name": "Re-Education Camp",
        "description": "Suspends target's rating for 2h. No gains or losses recorded during this period.",
        "cost": 12000,
        "requires_target": True,
        "requires_text": False,
        "duration": 7200,
        "category": "core",
    },
    # --- Economy / interaction ---
    "lottery": {
        "name": "People's Lottery",
        "description": "70% loss · 20% win ¥600–1,000 · 10% jackpot ¥2,000–4,000. Gift-eligible.",
        "cost": 500,
        "requires_target": False,
        "requires_text": False,
        "category": "lottery",
    },
    "lottery_standard": {
        "name": "Workers' Lottery",
        "description": "70% loss · 20% win ¥3,000–5,000 · 10% jackpot ¥10,000–20,000. Gift-eligible.",
        "cost": 2500,
        "requires_target": False,
        "requires_text": False,
        "category": "lottery",
    },
    "lottery_premium": {
        "name": "Cadre Lottery",
        "description": "70% loss · 20% win ¥12,000–18,000 · 10% jackpot ¥40,000–80,000. Gift-eligible.",
        "cost": 10000,
        "requires_target": False,
        "requires_text": False,
        "category": "lottery",
    },
    "lottery_elite": {
        "name": "Politburo Lottery",
        "description": "70% loss · 20% win ¥60,000–90,000 · 10% jackpot ¥200,000–400,000. Gift-eligible.",
        "cost": 50000,
        "requires_target": False,
        "requires_text": False,
        "category": "lottery",
    },
    "lottery_chairman": {
        "name": "Chairman's Lottery",
        "description": "70% loss · 20% win ¥300,000–500,000 · 10% jackpot ¥1,000,000–2,000,000. Gift-eligible.",
        "cost": 250000,
        "requires_target": False,
        "requires_text": False,
        "category": "lottery",
    },
    "lottery_dono": {
        "name": "Double or Nothing",
        "description": "Wager your entire balance. 50% chance to double it. 50% chance to lose everything. Cannot be gifted.",
        "cost": 0,
        "requires_target": False,
        "requires_text": False,
        "category": "lottery",
    },
    "model_citizen": {
        "name": "Model Citizen Award",
        "description": "Grants +2.00 rating to yourself or another citizen. 1h cooldown.",
        "cost": 5000,
        "requires_target": False,
        "requires_text": False,
        "category": "economy",
    },
    "dispute": {
        "name": "Dispute Resolution",
        "description": "Arbitrated coin flip against target. Winner +5.00 · loser -5.00 rating.",
        "cost": 5000,
        "requires_target": True,
        "requires_text": False,
        "category": "economy",
    },
    "investigation": {
        "name": "Special Investigation",
        "description": "Places a 24h bounty on target. Your ¥8,000 is the reward. Add a reason to increase the payout.",
        "cost": 8000,
        "requires_target": True,
        "requires_text": False,
        "duration": 86400,
        "category": "economy",
    },
    "protection": {
        "name": "Political Protection",
        "description": "Halves the next incoming attack against target. Consumed on use. One active per citizen.",
        "cost": 7000,
        "requires_target": True,
        "requires_text": False,
        "category": "economy",
    },
    "inquiry": {
        "name": "Internal Inquiry",
        "description": "Reveals the identity of the last citizen to file a report or denouncement against you.",
        "cost": 4000,
        "requires_target": False,
        "requires_text": False,
        "category": "economy",
    },
    "criticism": {
        "name": "Coordinated Criticism",
        "description": "Doubles all incoming rating penalties against target for 24h.",
        "cost": 10000,
        "requires_target": True,
        "requires_text": False,
        "duration": 86400,
        "category": "economy",
    },
    # --- Chaos / system pressure ---
    "legal_rep": {
        "name": "Legal Representation",
        "description": "Halves all incoming rating penalties for 12h. Gift-eligible.",
        "cost": 8000,
        "requires_target": False,
        "requires_text": False,
        "duration": 43200,
        "category": "misc",
    },
    "anon_identity": {
        "name": "Alternate Identity",
        "description": "Your next report or denouncement is filed as Unknown Citizen. 24h window.",
        "cost": 10000,
        "requires_target": False,
        "requires_text": False,
        "duration": 86400,
        "category": "misc",
    },
    "immunity": {
        "name": "Citizen Immunity",
        "description": "50% chance to fully nullify the next negative action against this citizen. Gift-eligible.",
        "cost": 7500,
        "requires_target": False,
        "requires_text": False,
        "category": "misc",
    },
    "media_coverage": {
        "name": "State Media Coverage",
        "description": "Immediately grants +4.00 rating. Broadcast publicly. Gift-eligible.",
        "cost": 15000,
        "requires_target": False,
        "requires_text": False,
        "category": "misc",
    },
    # --- Cosmetics / prestige ---
    "verified": {
        "name": "Certified Normal",
        "description": "The Bureau certifies this citizen is, at minimum, normal. Cosmetic badge · server-wide.",
        "cost": 30000,
        "requires_target": False,
        "requires_text": False,
        "category": "cosmetic",
        "cosmetic": True,
    },
    "figure": {
        "name": "Neighbourhood Snitch",
        "description": "Dedication to reporting neighbours has been formally recognised. Cosmetic badge · server-wide.",
        "cost": 50000,
        "requires_target": False,
        "requires_text": False,
        "category": "cosmetic",
        "cosmetic": True,
    },
    "influencer": {
        "name": "Propaganda Mouthpiece",
        "description": "The Bureau has designated this citizen as an official Party voice. Cosmetic badge · server-wide.",
        "cost": 100000,
        "requires_target": False,
        "requires_text": False,
        "category": "cosmetic",
        "cosmetic": True,
    },
    "associate": {
        "name": "Sycophant Elite",
        "description": "Loyalty elevated above ordinary citizens. Recognised by the Party. Cosmetic badge · server-wide.",
        "cost": 150000,
        "requires_target": False,
        "requires_text": False,
        "category": "cosmetic",
        "cosmetic": True,
    },
    "asset": {
        "name": "State-Owned",
        "description": "This citizen is no longer a person. Classified as property of the People's Republic. Cosmetic badge · server-wide.",
        "cost": 250000,
        "requires_target": False,
        "requires_text": False,
        "category": "cosmetic",
        "cosmetic": True,
    },
    # --- Waifu Bureau upgrades ---
    "gacha_slots": {
        "name": "Wishlist Slots",
        "description": "Tier 1->15 · Tier 2->20 · Tier 3->25 · Tier 4->30 wishlist slots.",
        "cost": 0,
        "requires_target": False,
        "requires_text": False,
        "category": "gacha",
    },
    "gacha_rolls": {
        "name": "Bonus Rolls",
        "description": "Tier 1->+2 · Tier 2->+5 · Tier 3->+10 · Tier 4->+20 bonus rolls/hr.",
        "cost": 0,
        "requires_target": False,
        "requires_text": False,
        "category": "gacha",
    },
    "gacha_spawn": {
        "name": "Wishlist Spawn",
        "description": "Base 6% · Tier 1->7.5% · Tier 2->9.4% · Tier 3->11.7% · Tier 4->15% wishlist spawn rate.",
        "cost": 0,
        "requires_target": False,
        "requires_text": False,
        "category": "gacha",
    },
    "eternal_chairman": {
        "name": "Winnie the Pooh",
        "description": "Forbidden in 1.4 billion territories. Display name rendered in fullwidth script across every server the Bureau inhabits. Global cosmetic.",
        "cost": 25_025_025,
        "requires_target": False,
        "requires_text": False,
        "category": "cosmetic",
        "cosmetic": True,
        "global": True,
    },
}

BADGE_DISPLAY = {
    "verified":   "Verified Citizen",
    "figure":     "Community Figure",
    "influencer": "Regional Influencer",
    "associate":  "Party Associate",
    "asset":      "National Asset",
}

COSMETIC_META = {
    "verified":         {"color": 0x5DADE2, "label": "CERTIFIED NORMAL",       "suffix": " |【 𝖢𝖾𝗋𝗍𝗂𝖿𝗂𝖾𝖽 𝖭𝗈𝗋𝗆𝖺𝗅 】",                          "note": "You have been certified normal by the bureau. Server-wide status."},
    "figure":           {"color": 0x27AE60, "label": "NEIGHBOURHOOD SNITCH",   "suffix": " |〖 𝘕𝘦𝘪𝘨𝘩𝘣𝘰𝘶𝘳𝘩𝘰𝘰𝘥 𝘚𝘯𝘪𝘵𝘤𝘩 〗",                      "note": "Your dedication to reporting neighbours has been recognised. Server-wide status."},
    "influencer":       {"color": 0x8E44AD, "label": "PROPAGANDA MOUTHPIECE",  "suffix": " | 〔  ▰▰  𝙋𝙍𝙊𝙋𝘼𝙂𝘼𝙉𝘿𝘼 𝙈𝙊𝙐𝙏𝙃𝙋𝙄𝙀𝘾𝙀  ▰▰  〕",         "note": "The bureau has selected you as an official voice of the Party. Server-wide status."},
    "associate":        {"color": 0xCC0000, "label": "SYCOPHANT ELITE",         "suffix": " |【 𝘚𝘺𝘤𝘰𝘱𝘩𝘢𝘯𝘵 𝘌𝘭𝘪𝘵𝘦 】",                              "note": "Your loyalty has elevated you above ordinary citizens. Server-wide status."},
    "asset":            {"color": 0xF39C12, "label": "STATE-OWNED",             "suffix": " | ╠══ 𝙎𝙏𝘼𝙏𝙀-𝙊𝙒𝙉𝙀𝘿 ══╣",                                "note": "You are no longer a person. You are an asset of the People's Republic. Server-wide status."},
    "eternal_chairman": {"color": 0xFFB347, "label": "WINNIE THE POOH",         "suffix": " | ▓▒░【 𝙒𝙞𝙣𝙣𝙞𝙚 𝙩𝙝𝙚 𝙋𝙤𝙤𝙝 】░▒▓",                        "note": "Forbidden in 1.4 billion territories. Your name now renders in the sacred fullwidth script across every server the bureau inhabits. Global status."},
    "voter":            {"color": 0xE74C3C, "label": "LOYAL PATRIOT",           "suffix": " | ⟦ 𝘓𝘰𝘺𝘢𝘭 𝘗𝘢𝘵𝘳𝘪𝘰𝘵 ⟧",                                  "note": "Recognised for casting a ballot on the foreign registry Top.gg. Lasts 12 hours · vote again to renew. Recognised on every server the bureau inhabits."},
}

GACHA_UPGRADE_TIERS = {
    "gacha_slots": {
        "key":   "wishlist_slots",
        "costs": [20_000, 80_000, 300_000, 1_000_000],
        "values": [15, 20, 25, 30],
        "unit":  "wishlist slots",
    },
    "gacha_rolls": {
        "key":   "roll_bonus",
        "costs": [15_000, 75_000, 350_000, 1_200_000],
        "values": [2, 5, 10, 20],
        "unit":  "bonus rolls/hr",
    },
    "gacha_spawn": {
        "key":   "wishlist_spawn",
        "costs": [25_000, 125_000, 500_000, 1_500_000],
        "values": [7.5, 9.4, 11.7, 15.0],
        "unit":  "% wishlist spawn rate",
    },
}
