SHOP_ITEMS = {
    # --- Core system ---
    "report": {
        "name": "Citizen Report",
        "description": "Docks a target 2 score points. Files an official report.",
        "cost": 2500,
        "requires_target": True,
        "requires_text": False,
        "category": "core",
    },
    "denounce": {
        "name": "Public Denouncement",
        "description": "Posts a public denouncement. Docks target 20 score points.",
        "cost": 6000,
        "requires_target": True,
        "requires_text": True,
        "category": "core",
    },
    "surveillance": {
        "name": "Surveillance Dossier",
        "description": "Unlocks one use of /surveillance_report on a target within 30 days.",
        "cost": 2000,
        "requires_target": True,
        "requires_text": False,
        "duration": 2592000,
        "category": "core",
    },
    "rehabilitate": {
        "name": "Rehabilitation Program",
        "description": "Restores +3 score. Cost doubles each use.",
        "cost": 3000,
        "requires_target": False,
        "requires_text": False,
        "category": "core",
    },
    "appeal": {
        "name": "Appeal Process",
        "description": "Next incoming report or penalty is reduced 50% within 12 hours. Single use.",
        "cost": 4000,
        "requires_target": False,
        "requires_text": False,
        "duration": 43200,
        "category": "core",
    },
    "exception": {
        "name": "Administrative Exception",
        "description": "Completely cancels the next negative score action against you within 24 hours.",
        "cost": 12000,
        "requires_target": False,
        "requires_text": False,
        "duration": 86400,
        "category": "core",
    },
    "reeducation": {
        "name": "Re-Education Camp",
        "description": "Freezes a target's score for 2 hours. No gains or losses from any source.",
        "cost": 20000,
        "requires_target": True,
        "requires_text": False,
        "duration": 7200,
        "category": "core",
    },
    # --- Economy / interaction ---
    "lottery": {
        "name": "State Lottery",
        "description": "50% lose entry · 40% gain 500-1000 · 10% gain 2000+. RNG yuan sink.",
        "cost": 500,
        "requires_target": False,
        "requires_text": False,
        "category": "economy",
    },
    "tip": {
        "name": "Anonymous Tip",
        "description": "Posts a public message about a target appearing from Unknown Citizen.",
        "cost": 750,
        "requires_target": True,
        "requires_text": True,
        "category": "economy",
    },
    "model_citizen": {
        "name": "Model Citizen Award",
        "description": "Instantly adds +1 score to yourself.",
        "cost": 1000,
        "requires_target": False,
        "requires_text": False,
        "category": "economy",
    },
    "dispute": {
        "name": "Dispute Resolution",
        "description": "Challenges a citizen to a coin flip. Winner gains +2 score, loser loses -2.",
        "cost": 1500,
        "requires_target": True,
        "requires_text": False,
        "category": "economy",
    },
    "investigation": {
        "name": "Special Investigation",
        "description": "Places a 24h bounty on a target. Next person to report them earns ¥2,500 bonus.",
        "cost": 8000,
        "requires_target": True,
        "requires_text": False,
        "duration": 86400,
        "category": "economy",
    },
    "protection": {
        "name": "Political Protection",
        "description": "Shields an ally for 24h. First negative action against them is reduced by 50%.",
        "cost": 7000,
        "requires_target": True,
        "requires_text": False,
        "duration": 86400,
        "category": "economy",
    },
    "inquiry": {
        "name": "Internal Inquiry",
        "description": "Reveals the last citizen who filed a report or denouncement against you.",
        "cost": 4000,
        "requires_target": False,
        "requires_text": False,
        "category": "economy",
    },
    "criticism": {
        "name": "Coordinated Criticism",
        "description": "For 24h, all negative score actions against a target deal double score loss.",
        "cost": 10000,
        "requires_target": True,
        "requires_text": False,
        "duration": 86400,
        "category": "economy",
    },
    # --- Chaos / system pressure ---
    "inspection": {
        "name": "Compliance Inspection",
        "description": "Randomly selects a citizen and applies -1 score. Outcome is unpredictable.",
        "cost": 3500,
        "requires_target": False,
        "requires_text": False,
        "category": "chaos",
    },
    "history_review": {
        "name": "Historical Review",
        "description": "Shows the last 20 score events for a target. Pure information advantage.",
        "cost": 9000,
        "requires_target": True,
        "requires_text": False,
        "category": "chaos",
    },
    "legal_rep": {
        "name": "Legal Representation",
        "description": "For 12h, all negative score actions against you deal 50% less score loss.",
        "cost": 8000,
        "requires_target": False,
        "requires_text": False,
        "duration": 43200,
        "category": "chaos",
    },
    "anon_identity": {
        "name": "Alternate Identity",
        "description": "Your next report or denouncement appears as Unknown Citizen. Single use.",
        "cost": 10000,
        "requires_target": False,
        "requires_text": False,
        "duration": 86400,
        "category": "chaos",
    },
    "immunity": {
        "name": "Citizen Immunity",
        "description": "50% chance to completely block the next negative action against you. Single use.",
        "cost": 7500,
        "requires_target": False,
        "requires_text": False,
        "category": "chaos",
    },
    "pact": {
        "name": "Mutual Assistance Pact",
        "description": "You and an ally both receive a 50% reduction shield on your next incoming penalty.",
        "cost": 6000,
        "requires_target": True,
        "requires_text": False,
        "duration": 86400,
        "category": "chaos",
    },
    "media_coverage": {
        "name": "State Media Coverage",
        "description": "Your next organic positive score gain is doubled and broadcast publicly.",
        "cost": 15000,
        "requires_target": False,
        "requires_text": False,
        "duration": 86400,
        "category": "chaos",
    },
    "fabricated_evidence": {
        "name": "Fabricated Evidence",
        "description": "Inserts a fake event into a target's score history. Psychological disruption only.",
        "cost": 3000,
        "requires_target": True,
        "requires_text": True,
        "category": "chaos",
    },
    # --- Cosmetics / prestige ---
    "verified": {
        "name": "Verified Citizen",
        "description": "Cosmetic badge. Displays verified status on your profile.",
        "cost": 30000,
        "requires_target": False,
        "requires_text": False,
        "category": "cosmetic",
        "cosmetic": True,
    },
    "figure": {
        "name": "Community Figure",
        "description": "Cosmetic badge. Profile highlighted in leaderboard lists.",
        "cost": 50000,
        "requires_target": False,
        "requires_text": False,
        "category": "cosmetic",
        "cosmetic": True,
    },
    "influencer": {
        "name": "Regional Influencer",
        "description": "Cosmetic badge. Larger profile presence.",
        "cost": 100000,
        "requires_target": False,
        "requires_text": False,
        "category": "cosmetic",
        "cosmetic": True,
    },
    "associate": {
        "name": "Party Associate",
        "description": "Rare cosmetic status title. Prestige only.",
        "cost": 150000,
        "requires_target": False,
        "requires_text": False,
        "category": "cosmetic",
        "cosmetic": True,
    },
    "asset": {
        "name": "National Asset",
        "description": "Top-tier cosmetic. Permanent leaderboard styling.",
        "cost": 250000,
        "requires_target": False,
        "requires_text": False,
        "category": "cosmetic",
        "cosmetic": True,
    },
    "eternal_chairman": {
        "name": "Winnie the Pooh",
        "description": "Global cosmetic. Forbidden in 1.4 billion territories. Your display name renders in fullwidth unicode across all servers.",
        "cost": 25_025_025,
        "requires_target": False,
        "requires_text": False,
        "category": "cosmetic",
        "cosmetic": True,
        "global": True,
    },
}

BADGE_DISPLAY = {
    "verified":   "Verified Citizen",
    "figure":     "Community Figure",
    "influencer": "Regional Influencer",
    "associate":  "Party Associate",
    "asset":      "National Asset",
}

COSMETIC_META = {
    "verified":         {"color": 0x5DADE2, "label": "VERIFIED CITIZEN",    "note": "Your identity has been verified by the bureau. Server-wide status."},
    "figure":           {"color": 0x27AE60, "label": "COMMUNITY FIGURE",    "note": "Your community standing has been formally recognized. Server-wide status."},
    "influencer":       {"color": 0x8E44AD, "label": "REGIONAL INFLUENCER", "note": "The bureau acknowledges your regional influence. Server-wide status."},
    "associate":        {"color": 0xCC0000, "label": "PARTY ASSOCIATE",     "note": "Your association with the Party has been formalized. Server-wide status."},
    "asset":            {"color": 0xF39C12, "label": "NATIONAL ASSET",      "note": "You have been designated a National Asset of the People's Republic. Server-wide status."},
    "eternal_chairman": {"color": 0xFFB347, "label": "WINNIE THE POOH",     "note": "Forbidden in 1.4 billion territories. Your name now renders in the sacred fullwidth script across every server the bureau inhabits. Global status."},
}
